In [1]:
import pandas as pd

In [4]:
df=pd.read_csv('horse.csv')

In [6]:
df.head(10)

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,...,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,no,adult,530101,38.5,66.0,28.0,cool,reduced,NaN,more_3_sec,...,45.0,8.4,NaN,NaN,died,no,11300,0,0,no
1,yes,adult,534817,39.2,88.0,20.0,NaN,NaN,pale_cyanotic,less_3_sec,...,50.0,85.0,cloudy,2.0,euthanized,no,2208,0,0,no
2,no,adult,530334,38.3,40.0,24.0,normal,normal,pale_pink,less_3_sec,...,33.0,6.7,NaN,NaN,lived,no,0,0,0,yes
3,yes,young,5290409,39.1,164.0,84.0,cold,normal,dark_cyanotic,more_3_sec,...,48.0,7.2,serosanguious,5.3,died,yes,2208,0,0,yes
4,no,adult,530255,37.3,104.0,35.0,NaN,NaN,dark_cyanotic,more_3_sec,...,74.0,7.4,NaN,NaN,died,no,4300,0,0,no
5,no,adult,528355,NaN,NaN,NaN,warm,normal,pale_pink,less_3_sec,...,NaN,NaN,NaN,NaN,lived,no,0,0,0,no
6,yes,adult,526802,37.9,48.0,16.0,normal,normal,normal_pink,less_3_sec,...,37.0,7.0,NaN,NaN,lived,yes,3124,0,0,no
7,yes,adult,529607,NaN,60.0,NaN,cool,NaN,NaN,less_3_sec,...,44.0,8.3,NaN,NaN,died,yes,2208,0,0,no
8,no,adult,530051,NaN,80.0,36.0,cool,absent,pale_pink,less_3_sec,...,38.0,6.2,NaN,NaN,euthanized,yes,3205,0,0,no
9,no,young,5299629,38.3,90.0,NaN,normal,NaN,normal_pink,less_3_sec,...,40.0,6.2,clear,2.2,lived,no,0,0,0,yes

In [8]:
df.fillna(0).head(10)

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,...,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,no,adult,530101,38.5,66.0,28.0,cool,reduced,0,more_3_sec,...,45.0,8.4,0,0.0,died,no,11300,0,0,no
1,yes,adult,534817,39.2,88.0,20.0,0,0,pale_cyanotic,less_3_sec,...,50.0,85.0,cloudy,2.0,euthanized,no,2208,0,0,no
2,no,adult,530334,38.3,40.0,24.0,normal,normal,pale_pink,less_3_sec,...,33.0,6.7,0,0.0,lived,no,0,0,0,yes
3,yes,young,5290409,39.1,164.0,84.0,cold,normal,dark_cyanotic,more_3_sec,...,48.0,7.2,serosanguious,5.3,died,yes,2208,0,0,yes
4,no,adult,530255,37.3,104.0,35.0,0,0,dark_cyanotic,more_3_sec,...,74.0,7.4,0,0.0,died,no,4300,0,0,no
5,no,adult,528355,0.0,0.0,0.0,warm,normal,pale_pink,less_3_sec,...,0.0,0.0,0,0.0,lived,no,0,0,0,no
6,yes,adult,526802,37.9,48.0,16.0,normal,normal,normal_pink,less_3_sec,...,37.0,7.0,0,0.0,lived,yes,3124,0,0,no
7,yes,adult,529607,0.0,60.0,0.0,cool,0,0,less_3_sec,...,44.0,8.3,0,0.0,died,yes,2208,0,0,no
8,no,adult,530051,0.0,80.0,36.0,cool,absent,pale_pink,less_3_sec,...,38.0,6.2,0,0.0,euthanized,yes,3205,0,0,no
9,no,young,5299629,38.3,90.0,0.0,normal,0,normal_pink,less_3_sec,...,40.0,6.2,clear,2.2,lived,no,0,0,0,yes

In [9]:
from sklearn.preprocessing import LabelEncoder

In [42]:
l=LabelEncoder()
surgical_label=LabelEncoder()
cp_data_label=LabelEncoder()
age_label=LabelEncoder()
main_target=LabelEncoder()

In [43]:
df.columns

Index(['surgery', 'age', 'hospital_number', 'rectal_temp', 'pulse',
       'respiratory_rate', 'temp_of_extremities', 'peripheral_pulse',
       'mucous_membrane', 'capillary_refill_time', 'pain', 'peristalsis',
       'abdominal_distention', 'nasogastric_tube', 'nasogastric_reflux',
       'nasogastric_reflux_ph', 'rectal_exam_feces', 'abdomen',
       'packed_cell_volume', 'total_protein', 'abdomo_appearance',
       'abdomo_protein', 'outcome', 'surgical_lesion', 'lesion_1', 'lesion_2',
       'lesion_3', 'cp_data', 'Encoded_label', 'Surgical_label',
       'Cp_data_label', 'age_label', 'Surgery_label'],
      dtype='object')

In [44]:
df['Surgery_label']=l.fit_transform(df['surgery'])
df['Surgical_label']=surgical_label.fit_transform(df['surgical_lesion'])
df['Cp_data_label']=cp_data_label.fit_transform(df['cp_data'])
df['age_label']=age_label.fit_transform(df['age'])
df['Main_target']=main_target.fit_transform(df['outcome'])

In [47]:
#df.head(10)
df[['outcome','Main_target']].head(10)
#NO means 0
#YES means 1.

      outcome  Main_target
0        died            0
1  euthanized            1
2       lived            2
3        died            0
4        died            0
5       lived            2
6       lived            2
7        died            0
8  euthanized            1
9       lived            2

In [34]:
feature_n=df.drop(['surgery', 'age', 'hospital_number', 'rectal_temp', 'pulse',
       'respiratory_rate', 'temp_of_extremities', 'peripheral_pulse',
       'mucous_membrane', 'capillary_refill_time', 'pain', 'peristalsis',
       'abdominal_distention', 'nasogastric_tube', 'nasogastric_reflux',
       'nasogastric_reflux_ph', 'rectal_exam_feces', 'abdomen',
       'packed_cell_volume', 'total_protein', 'abdomo_appearance',
       'abdomo_protein', 'outcome', 'surgical_lesion', 'lesion_1', 'lesion_2',
       'lesion_3', 'cp_data', 'Encoded_label'],axis='columns')

In [35]:
feature_n.head(4)

   Surgical_label  Cp_data_label  age_label  Surgery_label
0               0              0          0              0
1               0              0          0              1
2               0              1          0              0
3               1              1          1              1

In [50]:
target=df['Main_target']
target.head(10)

0    0
1    1
2    2
3    0
4    0
5    2
6    2
7    0
8    1
9    2
Name: Main_target, dtype: int32

In [51]:
from sklearn import tree
model=tree.DecisionTreeClassifier()
model.fit(feature_n,target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [52]:
model.score(feature_n,target)

0.6488294314381271

In [53]:
model.predict([[0,1,0,0]])

array([2])

#from sklearn.model_selection import train_test_split
#X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=.20,random_state=10)

#from sklearn import tree
#model=tree.DecisionTreeClassifier()
#model.fit